[server]
headless = true
enableCORS = false

[tableau]
token_name = "streamlit-app"
token_secret = "1kJyEb4eQPG3rfmvFlRGXA==:V2fT6ZiNfG4bWUd4z7PD45aG6ecg9fYr"
server_url = "https://prod-apsoutheast-a.online.tableau.com/"
site_id = "#/site/kaalakoota"  # in your site's URL behind the server_url